image: alpine/edge
packages:
  - go
sources:
  - https://git.sr.ht/~mariusor/ssm
tasks:
  - tests: |
      export GOMODCACHE=$(go env GOMODCACHE)

      cd ssm
      go test -cover -race -v ./...

      cd ./cmd/tests
      go test -cover -race -v ./...
