image: alpine/edge
packages:
  - go
sources:
  - https://git.sr.ht/~mariusor/ssm
tasks:
  - tests: |
      export GOMODCACHE=$(go env GOMODCACHE)
      go install git.sr.ht/~mariusor/ssm@latest || true

      cd ssm
      go mod tidy
      go test -cover -race -v ./...

      cd cmd
      go mod tidy
      go test -cover -race -v ./...
